// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qfejcreecaenastsrtwg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFmZWpjcmVlY2FlbmFzdHNydHdnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI1MDQ2NzYsImV4cCI6MjA1ODA4MDY3Nn0.c4wBkzDfzrpSLnKPCdRtqwJr6ZvKPW1ksTiTDN_9Yy8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);